version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: rest-cycle-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rest-cycle
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: rest-cycle-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/rest-cycle
      NODE_ENV: production
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: rest-cycle-ui
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data: